ol_shop_project/ol_shop_project/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/', include('show_products.urls')),
    path('register/', user_views.register_user, name='register'),
    path('login/',
         auth_views.LoginView.as_view(template_name='users/login.html'),
         name='login'),
    path('logout/',
         auth_views.LogoutView.as_view(template_name='users/logout.html'),
         name='logout'),
    path('profile/', user_views.profile_page, name='profile'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ol_shop_project/show_products/urls.py
from django.urls import path
from . import views

app_name = 'show_products'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.ItemDetail.as_view(), name='detail'),
    path('add', views.CreateItem.as_view(), name='add_item'),
    path('update/<int:item_id>/', views.update_item, name='update_item'),
    path('delete/<int:item_id>/', views.delete_item, name='delete_item'),
]

ol_shop_project/show_products/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


# Create your models here.
class Item(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=200)
    price = models.IntegerField()
    image = models.CharField(max_length=500,
                             default="https://derdafoods.com/static/backend/"
                                     "img/meal-placeholder.jpg")
    userid = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('show_products:detail', kwargs={'pk': self.pk})

ol_shop_project/users/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='profile_img.jpg',
                              upload_to='profile_pictures')
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

ol_shop_project/show_products/forms.py
from django import forms
from .models import Item


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['name', 'description', 'price', 'image']

ol_shop_project/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta():
        model = User
        fields = ['username', 'email', 'password1', 'password2']

ol_shop_project/show_products/views.py
from django.shortcuts import render, redirect
from .models import Item
from .forms import ItemForm
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView


class IndexView(ListView):
    model = Item
    template_name = 'show_products/index.html'
    context_object_name = 'item_list'


class ItemDetail(DetailView):
    model = Item
    template_name = 'show_products/detail.html'


class CreateItem(CreateView):
    model = Item
    template_name = 'show_products/item_form.html'
    fields = ['name', 'description', 'price', 'image']

    def form_valid(self, form):
        form.instance.userid = self.request.user

        return super().form_valid(form)


def update_item(request, item_id):
    item = Item.objects.get(id=item_id)
    form = ItemForm(request.POST or None, instance=item)
    context = {'form': form, 'item': item}

    if form.is_valid():
        form.save()
        return redirect('show_products:index')
    return render(request, 'show_products/item_form.html', context)


def delete_item(request, item_id):
    item = Item.objects.get(id=item_id)
    context = {'item': item}
    if request.method == 'POST':
        item.delete()
        return redirect('show_products:index')
    return render(request, 'show_products/del_item.html', context)

ol_shop_project/users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import RegisterForm


def register_user(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, 'Signed in correctly. Welcome, '
                                      f'{username}!')
            return redirect('login')
    else:
        form = RegisterForm()
    context = {'form': form}
    return render(request, 'users/reg_user.html', context)


@login_required
def profile_page(request):
    return render(request, 'users/profile.html')

ol_shop_project/show_products/templates/show_products/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet", href="{% static 'show_products/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css"
          rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0"
          crossorigin="anonymous"></script>

</head>
<body>

    <nav class="navbar navbar-dark bg-dark">
        <a href="{% url 'show_products:index' %}" class="navbar-brand">Online Store</a>
        <div class="navbar">
            <a class="nav-item nav-link" href=" {% url 'show_products:add_item' %}">Add Item</a>
            {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                <a class="nav-item nav-link" href="{% url 'logout' %}">Log out</a>
            {% else %}
                <a class="nav-item nav-link" href="{% url 'login' %}">Log in</a>
            {% endif %}
        </div>
    </nav>
    {% if messages %}
        {% for m in messages %}
            <div class="alert alert-{{ m.tags }} text-center">
                {{ m }}
            </div>
        {% endfor %}
    {% endif %}
    {% block body %}
    {% endblock %}

</body>
</html>

ol_shop_project/show_products/templates/show_products/del_item.html
{% extends 'show_products/base.html' %}
{% block body %}
    <form method="POST">
        {% csrf_token %}
        <h3>Are you sure you want to delete {{ item.name }}?</h3>
        <button type="submit">Confirm</button>
    </form>
{% endblock %}

ol_shop_project/show_products/templates/show_products/detail.html
{% extends 'show_products/base.html' %}

{% block body %}

    <div class="container">
        <div class="row">

            <div class="col-md-6">
                <img src="{{ object.image }}" class="card" height="300px">
            </div>

            <div class="col-md-6">
                <h1>{{ object.name }}</h1>
                <h2>{{ object.description }}</h2>
                <h3>${{ object.price }}</h3>
                <a href="{% url 'show_products:delete_item' object.id %}">Delete</a>
            </div>

        </div>
    </div>
{% endblock %}

ol_shop_project/show_products/templates/show_products/index.html
{% extends 'show_products/base.html' %}

{% block body %}
    <h1>Available items</h1>

    {% for i in item_list %}
        <div class="row">
            <div class="col-md-3 offset-md-2">
                <img class="card" height="150px" src="{{ i.image }}">
            </div>
            <div class="col-md-4">
                <h3>{{ i.name }}</h3>
                <h5>{{ i.description }}</h5>
                <h6>${{ i.price }}</h6>
            </div>
            <div class="col-md-2">
                <a href="{% url 'show_products:detail' i.id %}" class="btn btn-success">Detail</a>
            </div>

        </div>
    {% endfor %}


{% endblock %}

ol_shop_project/show_products/templates/show_products/item_form.html
{% extends 'show_products/base.html' %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-4 offset-md-4">
                <div class="card">
                    <div class="card-header bg-info text-white">
                        <div class="card-title">
                            Add item
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            {% for f in form %}
                                <div class="form-group">
                                    {{ f.name }}
                                    <br>
                                    {{ f }}
                                </div>
                            {% endfor %}
                            <button class="btn-info text-white" type="submit">Save</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

ol_shop_project/users/templates/users/login.html
{% extends 'show_products/base.html' %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-4 offset-md-4">
                <div class="card">
                    <div class="card-header text-white bg-info">
                        <div class="card-title">
                            Login
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            {% for f in form %}
                                <div class="form-group">
                                    {{ f.name }}
                                    {{ f }}
                                </div>
                            {% endfor %}
                            <button class="btn-info text-white" type="submit">Login</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

ol_shop_project/users/templates/users/logout.html
{% extends 'show_products/base.html' %}

{% block body %}
    <h1>Logged out</h1>
{% endblock %}

ol_shop_project/users/templates/users/profile.html
{% extends 'show_products/base.html' %}

{% block body %}
    <h1>{{ user.username }}</h1>
    <img width="100px" height="100px" src="{{ user.profile.image.url }}">
{% endblock %}

ol_shop_project/users/templates/users/reg_user.html
{% extends 'show_products/base.html' %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-4 offset-md-4">
                <div class="card">
                    <div class="card-header text-white bg-info">
                        <div class="card-title">
                            Register
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            {% for f in form %}
                                <div class="form-group">
                                    {{ f.name }}
                                    <br>
                                    {{ f }}
                                </div>
                            {% endfor %}
                            <button class="btn-info text-white" type="submit">Sign up</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}